spring:
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false

  datasource:
    url: jdbc:postgresql://localhost:5432/snjofko1
    username: snjofko
    password: snjofko

    security.basic.enabled: false